import { Component, inject, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatListModule } from '@angular/material/list';
import { McqService } from '../../../core/services/mcq.service';
import { SnackService } from '../../../core/services/snack.service';
import { BulkUploadResponse } from '../../../core/models';
import { ButtonDirective } from '../../../shared/components/button/button.directive';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';

@Component({
  selector: 'app-bulk-upload',
  standalone: true,
  imports: [
    DecimalPipe, MatCardModule, MatButtonModule, MatIconModule,
    MatProgressBarModule, MatListModule, ButtonDirective, PageHeaderComponent
  ],
  templateUrl: './bulk-upload.component.html',
})
export class BulkUploadComponent {
  private mcqSvc = inject(McqService);
  private snack  = inject(SnackService);

  selectedFile = signal<File | null>(null);
  uploading    = signal(false);
  result       = signal<BulkUploadResponse | null>(null);
  dragOver     = signal(false);

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files?.[0]) this.setFile(input.files[0]);
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.dragOver.set(false);
    const file = event.dataTransfer?.files[0];
    if (file) this.setFile(file);
  }

  private setFile(file: File): void {
    if (!file.name.endsWith('.xlsx')) {
      this.snack.error('Only .xlsx files are supported');
      return;
    }
    this.selectedFile.set(file);
    this.result.set(null);
  }

  upload(): void {
    const file = this.selectedFile();
    if (!file || this.uploading()) return;
    this.uploading.set(true);

    this.mcqSvc.bulkUpload(file).subscribe({
      next: res => {
        this.result.set(res.data);
        this.uploading.set(false);
        if (res.data.failureCount === 0) {
          this.snack.success(`${res.data.successCount} questions uploaded successfully`);
        } else {
          this.snack.error(`${res.data.failureCount} rows failed. Review errors below.`);
        }
      },
      error: err => {
        this.snack.error(err.error?.message ?? 'Upload failed');
        this.uploading.set(false);
      }
    });
  }

  reset(): void {
    this.selectedFile.set(null);
    this.result.set(null);
  }

  downloadingTemplate = signal(false);

  /** Downloads the real .xlsx template generated by the backend (same layout as export). */
  downloadTemplate(): void {
    if (this.downloadingTemplate()) return;
    this.downloadingTemplate.set(true);
    this.mcqSvc.downloadImportTemplate().subscribe({
      next: blob => {
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'question-import-template.xlsx';
        a.click();
        URL.revokeObjectURL(a.href);
        this.downloadingTemplate.set(false);
      },
      error: () => { this.snack.error('Could not download template'); this.downloadingTemplate.set(false); }
    });
  }
}
